apiVersion: v1
kind: Service
metadata:
  name: {{ include "interdict.fullname" . }}-kernel
  labels:
    {{- include "interdict.labels" . | nindent 4 }}
    app.kubernetes.io/component: kernel
spec:
  type: {{ .Values.kernel.service.type }}
  ports:
    - name: https
      port: {{ .Values.kernel.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "interdict.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kernel
