apiVersion: v1
kind: Service
metadata:
  name: {{ include "interdict.fullname" . }}-control-plane
  labels:
    {{- include "interdict.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - name: http
      port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.controlPlane.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "interdict.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
